"""
Experiment 029 — memory_lambda_calibration.py (★ group-blind interface-capacity calibration ★)
==============================================================================================

Run:  python memory_lambda_calibration.py

--------------------------------------------------------------------------------
The question the calibration answers (★ nothing to do with "which λ makes 029 succeed" ★)
-----------------------------------------------------------------------------------------
    ┌──────────────────────────────────────────────────────────────────┐
    │  Once real memory input passes through this interface, can a single decision   │
    │  receive an influence that is **neither saturated nor negligible**?            │
    └──────────────────────────────────────────────────────────────────┘

⛔ It is **not**: "which λ most easily makes 029 succeed / separates the two groups most?"

--------------------------------------------------------------------------------
★★ group-blindness here is structural, not a matter of self-discipline ★★
-------------------------------------------------------------------------
The input is the m naturally generated by `memory_acquisition_probe.py` (the frozen ANOMALY_AT=36 version),
**but the condition label is stripped at the calibration layer**:

```
pooled_empirical_m()  →  a **sorted list of floats** of length 2×400;
                          sorting completely destroys the correspondence between m and Stable/Volatile,
                          and nothing in this file **can** recover the grouping.
```

- **agents with m = 0 are included** (those that grew no usable memory) — see rule 91:
  filtering them out before calibrating would systematically inflate the real input strength of the memory channel.
- This file **contains** no code path that groups by condition.

--------------------------------------------------------------------------------
Only these are reported
-----------------------
```
✅ mean |Δp| / median |Δp| / p90 |Δp|      how far a single decision is pushed
✅ decision saturation                     whether there is any choice left after the push
✅ active-memory exposure                  whether memory is still event-triggered
✅ P(preference flip)                      the share where memory tips the argmax across 0.5
⛔ Stable vs Volatile ΔC                   ⛔ Stable vs Volatile latency
⛔ which λ separates the two groups best
```

The convention for `Δp`: **relative to the "no memory" counterfactual**

```
Δp(state, m, λ) = p_switch( z_base + λ·m·s )  −  p_switch( z_base )
```

The decision states come from the **memory-blind (λ=0) trajectory** (probe3's frozen-state pipeline),
so the states themselves carry no memory influence.

--------------------------------------------------------------------------------
The criteria for λ (decided by the user; all three must hold at once)
---------------------------------------------------------------------
```
① not saturated               after the push, p must not pile up at ≤0.05 / ≥0.95
② substantial but not excessive   a single decision must be movable, without memory "having the last word"
③ memory stays event-triggered    active exposure must not consume the whole task
```
**This file only prints the readings of these three plus a recommendation; freezing λ is the user's call.**
"""

import math
import statistics
import sys

import novel_task as NT
import memory_transfer_probe3 as P3
import memory_acquisition_probe as ACQ
from memory_transfer_probe import PROBE_SEEDS

BODY = ACQ.NeutralBody                      # neutral body for calibration
LAMBDA_GRID = (0.25, 0.5, 1.0, 2.0, 4.0, 8.0)
SAT_LO, SAT_HI = 0.05, 0.95

# ============================================================================
# ★★★ Formally frozen 2026-08-18 ★★★
#
# These four are **engineering admissibility gates**, not scientific significance
# thresholds. They were frozen **before any Stable/Volatile downstream transfer outcome
# had been seen** — and from that moment they are not changed for any outcome.
# ----------------------------------------------------------------------------
SATURATION_MAX      = 0.05   # share landing at p≤.05 or ≥.95 after the push — memory should not push more
                             # than 1/20 of eligible decisions to near-determinism
MEDIAN_ABS_DP_MIN   = 0.02   # minimum capability threshold — if it cannot move even a typical decision
                             # probability by 2 percentage points, the interface hardly entered the decision
PREF_FLIP_MAX       = 0.25   # memory may change some choices, but must not take over the argmax on a large
                             # share of eligible states. At most one flip in four
ACTIVE_EXPOSURE_MAX = 20     # /80 — pins event-triggeredness to "at most a quarter of the task".
                             # Measured at λ=1 it is only about 7/80; this mainly guards against future architectural drift
MEMORY_LAMBDA       = 1.00   # ★ formally frozen ★
# ----------------------------------------------------------------------------
# ★ The exposure gate uses max, not mean ★
#   Event-triggeredness must not allow "one memory sign is nearly always on
#   but gets averaged away by the other two". At λ=1 the maximum exposure is only 6.95/80, so the verdict is unaffected.
#
# ★★ Selection rule (fixed before the FINAL run, copied verbatim into the paper) ★★
#
#   Lambda was calibrated without condition labels or downstream transfer
#   outcomes. Values were required to satisfy prespecified interface-capacity
#   constraints on saturation, median probability shift, preference reversal,
#   and retrieval exposure. Among admissible values, the log-scale midpoint of
#   the admissible range was selected.
#
#   The passing band {0.5, 1.0, 2.0} lies on a doubling grid, and 1.0 = sqrt(0.5 × 2) is exactly its centre on a log scale.
#   ⚠ It is not "pick the largest potency" but "pick the point furthest from both failure directions".
#   → Nobody can later ask "would a different λ have made it positive?" — λ was frozen by interface properties
#     before any group transfer outcome was seen.
# ============================================================================


# ================================================================== input
def pooled_empirical_m():
    """★ group-blind ★ Returns a **sorted** list of m; the label is discarded inside this function.

    - the agents of both conditions are poured into one pool
    - **agents with m = 0 are included** (rule 91: no filtering by "did a memory grow")
    - after sorting, the correspondence between m and condition **cannot be recovered** within this module
    """
    pool = []
    for cond in ACQ.CONDITIONS:             # ← the label appears on this line only and is discarded at once
        for sd in PROBE_SEEDS:
            eps, _ = ACQ.acquire(sd, cond)
            m, _, _ = ACQ.evidence_of(eps)
            pool.append(float(m))
    pool.sort()                             # ★ destroys the grouping information ★
    assert len(pool) == len(PROBE_SEEDS) * len(ACQ.CONDITIONS)
    assert all(isinstance(x, float) for x in pool)
    return pool


class ConstantMemory:
    """Read a given m directly as evidence — used only for exposure measurement"""

    def __init__(self, m):
        self._m = float(m)
        self.name = f"m={self._m:+.4f}"

    def evidence(self, context):
        return (self._m, 1, 1) if context else (0.0, 0, 0)


def frozen_states(body):
    """Eligible decision states on the λ=0 memory-blind trajectory (probe3's pipeline)"""
    st = []
    for sd in PROBE_SEEDS:
        st += P3.run_fixed(body, ConstantMemory(0.0), sd, 0.0, trace=True)["states"]
    return st


def _sig(z):
    return 1.0 / (1.0 + math.exp(-max(-60.0, min(60.0, z))))


def _q(xs, f):
    return xs[min(len(xs) - 1, int(f * len(xs)))]


# ================================================================== report
def capacity_report(states, pool):
    print("\n" + "=" * 78)
    print("★ Interface capacity — how far a single decision is moved by real memory (against the no-memory counterfactual) ★")
    print("=" * 78)
    base = [_sig(z) for z, _ in states]
    base_sat = sum(1 for p in base if p <= SAT_LO or p >= SAT_HI) / len(base)
    print(f"  eligible decision states = {len(states)}"
          f"   ({len(states) / len(PROBE_SEEDS):.2f} per seed)")
    print(f"  base p(switch) with no memory: median {statistics.median(base):.3f}"
          f"   share already saturated {base_sat:.1%}")
    print(f"  pooled empirical m (including m=0): n={len(pool)}"
          f"  mean {statistics.fmean(pool):+.4f}"
          f"  median |m| {statistics.median([abs(x) for x in pool]):.4f}"
          f"  m=0 share {sum(1 for x in pool if x == 0.0) / len(pool):.1%}")
    print(f"\n{'λ':>6}{'mean|Δp|':>11}{'median|Δp|':>13}{'p90|Δp|':>10}"
          f"{'saturated after push':>22}{'P(preference flip)':>20}")
    print("-" * 78)
    out = {}
    for lam in LAMBDA_GRID:
        d, sat, flip, n = [], 0, 0, 0
        for z, s in states:
            p0 = _sig(z)
            for m in pool:
                p1 = _sig(z + lam * m * s)
                d.append(abs(p1 - p0))
                sat += p1 <= SAT_LO or p1 >= SAT_HI
                flip += (p0 - 0.5) * (p1 - 0.5) < 0
                n += 1
        d.sort()
        out[lam] = dict(mean=statistics.fmean(d), med=statistics.median(d),
                        p90=_q(d, .90), sat=sat / n, flip=flip / n)
        print(f"{lam:>6.2f}{out[lam]['mean']:>11.4f}{out[lam]['med']:>13.4f}"
              f"{out[lam]['p90']:>10.4f}{out[lam]['sat']:>10.1%}"
              f"{out[lam]['flip']:>13.1%}")
    return out


def exposure_report(pool):
    """③ is memory still event-triggered — measured with three representative m from the pooled distribution"""
    print("\n" + "=" * 78)
    print("★ active-memory exposure — has memory turned from event-triggered into always-on ★")
    print("=" * 78)
    reps = [_q(pool, .10), statistics.median(pool), _q(pool, .90)]
    pot = statistics.fmean(
        [sum(P3.run_fixed(BODY, ConstantMemory(0.0), sd, 0.0)["fired"])
         for sd in PROBE_SEEDS])
    print(f"  potential exposure (defined at λ=0) = {pot:.2f} / {NT.TRIALS} trials")
    print(f"\n{'λ':>6}" + "".join(f"{'realized @ m=' + f'{m:+.3f}':>22}" for m in reps))
    print("-" * 78)
    out = {}
    for lam in LAMBDA_GRID:
        row, vals = f"{lam:>6.2f}", []
        for m in reps:
            e = statistics.fmean(
                [sum(P3.run_fixed(BODY, ConstantMemory(m), sd, lam)["fired"])
                 for sd in PROBE_SEEDS])
            vals.append(e)
            row += f"{e:>22.2f}"
        out[lam] = vals
        print(row)
    print(f"\n  ⚠ Criterion ③: exposure must stay a small fraction of the {NT.TRIALS} trials."
          " If it rises, memory has become an always-on prior.")
    return out


def recommend(cap, exp):
    print("\n" + "=" * 78)
    print("★ Readings of the three criteria (freezing λ is the user's call; this file does not decide for you) ★")
    print("=" * 78)
    print(f"{'λ':>6}{'① not saturated':>20}{'② substantial, not excessive':>32}{'③ event-triggered':>22}")
    print("-" * 78)
    for lam in LAMBDA_GRID:
        c = cap[lam]
        e = max(exp[lam])          # ★ max, not mean ★
        ok1 = c["sat"] <= SATURATION_MAX
        ok2 = c["med"] >= MEDIAN_ABS_DP_MIN and c["flip"] <= PREF_FLIP_MAX
        ok3 = e <= ACTIVE_EXPOSURE_MAX
        col1 = ("✓ " if ok1 else "✗ ") + "{:.1%}".format(c["sat"])
        col2 = ("✓ " if ok2 else "✗ ") + "med {:.3f} flip {:.1%}".format(
            c["med"], c["flip"])
        col3 = ("✓ " if ok3 else "✗ ") + "{:.2f}/{}".format(e, NT.TRIALS)
        print(f"{lam:>6.2f}{col1:>12}{col2:>26}{col3:>20}")
    print("\n  ★ Frozen admissibility gates (2026-08-18) ★")
    print("    —— engineering gates, not significance thresholds;")
    print("       frozen before any Stable/Volatile transfer outcome had been seen.")
    print(f"    ① P(saturated after push) ≤ {SATURATION_MAX:.0%}")
    print(f"    ② median|Δp| ≥ {MEDIAN_ABS_DP_MIN} and P(preference flip) ≤ {PREF_FLIP_MAX:.0%}")
    print(f"    ③ ★max★(realized exposure @ m10/m50/m90) ≤ "
          f"{ACTIVE_EXPOSURE_MAX} / {NT.TRIALS}")

    band = [l for l in LAMBDA_GRID
            if cap[l]["sat"] <= SATURATION_MAX
            and cap[l]["med"] >= MEDIAN_ABS_DP_MIN
            and cap[l]["flip"] <= PREF_FLIP_MAX
            and max(exp[l]) <= ACTIVE_EXPOSURE_MAX]
    mid = math.sqrt(band[0] * band[-1])
    print(f"\n  Passing band = {band}")
    print(f"  ★ MEMORY_LAMBDA = {MEMORY_LAMBDA:.2f} is frozen ★"
          f"   log-scale centre of the band = sqrt({band[0]}×{band[-1]}) = {mid:.2f}")
    assert abs(mid - MEMORY_LAMBDA) < 1e-9, \
        "✗ the frozen λ is no longer the log centre of the passing band — the interface properties drifted, stop and investigate"
    print("\n  selection rule (copy verbatim into the paper):")
    print("    Lambda was calibrated without condition labels or downstream")
    print("    transfer outcomes. Values were required to satisfy prespecified")
    print("    interface-capacity constraints on saturation, median probability")
    print("    shift, preference reversal, and retrieval exposure. Among")
    print("    admissible values, the log-scale midpoint of the admissible")
    print("    range was selected.")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    print("=" * 78)
    print("029 λ CAPACITY CALIBRATION — ★group-blind; no transfer outcome is inspected★")
    print("=" * 78)
    print(f"acquisition: ANOMALY_AT={ACQ.ANOMALY_AT} ANOMALY_LEN={ACQ.ANOMALY_LEN}"
          f" T_PROBLEM={ACQ.T_PROBLEM} (still 22 after the anomaly)")
    print(f"task substrate 027 fingerprint {NT.assert_frozen()}   seeds "
          f"{PROBE_SEEDS[0]}–{PROBE_SEEDS[-1]}   ★80000–81499 untouched★")
    print("input = pooled empirical m (label discarded, m=0 included, sorted)")

    pool = pooled_empirical_m()
    states = frozen_states(BODY)
    cap = capacity_report(states, pool)
    exp = exposure_report(pool)
    recommend(cap, exp)

    print("\n" + "=" * 78)
    print("⛔ This file does not compute, and cannot compute: Stable vs Volatile ΔC / latency /")
    print("   which λ separates the two groups best — the condition label is discarded at the input.")
    print("=" * 78)
